// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20260712094246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Store.Models.Command", b =>
                {
                    b.Property<int>("CommandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<int>("TotalQuanity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommandID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("SellerID");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            CommandID = 1,
                            BuyerID = 3,
                            IsPaid = true,
                            SellerID = 1,
                            TotalPrice = 10m,
                            TotalQuanity = 8
                        },
                        new
                        {
                            CommandID = 2,
                            BuyerID = 2,
                            IsPaid = true,
                            SellerID = 1,
                            TotalPrice = 10m,
                            TotalQuanity = 3
                        },
                        new
                        {
                            CommandID = 3,
                            BuyerID = 3,
                            IsPaid = false,
                            SellerID = 1,
                            TotalPrice = 0m,
                            TotalQuanity = 2
                        });
                });

            modelBuilder.Entity("Store.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            BirthDate = new DateOnly(2000, 10, 2),
                            FirstName = "Nicolas",
                            LastName = "Martou"
                        },
                        new
                        {
                            PersonID = 2,
                            BirthDate = new DateOnly(1971, 6, 28),
                            FirstName = "Elon",
                            LastName = "Musk"
                        },
                        new
                        {
                            PersonID = 3,
                            BirthDate = new DateOnly(1955, 10, 28),
                            FirstName = "Bill",
                            LastName = "Gates"
                        });
                });

            modelBuilder.Entity("Store.Models.Price", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Discount")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DiscountEndDate")
                        .HasColumnType("DateTime");

                    b.Property<decimal>("Value")
                        .HasColumnType("money");

                    b.HasKey("PriceID");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            PriceID = 1,
                            Discount = 0f,
                            Value = 34.99m
                        },
                        new
                        {
                            PriceID = 2,
                            Discount = 15f,
                            DiscountEndDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19.99m
                        });
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.HasIndex("PriceID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Brand = "Micosoft",
                            Description = "This is our latest white hat which is very useful against the sun.",
                            Name = "White Hat",
                            PriceID = 1,
                            Stock = 42
                        },
                        new
                        {
                            ProductID = 2,
                            Brand = "MacroHard",
                            Description = "This object would fit perfectly with a white hat.",
                            Name = "T-shirt",
                            PriceID = 2,
                            Stock = 26
                        });
                });

            modelBuilder.Entity("Store.Models.ProductCommand", b =>
                {
                    b.Property<int>("ProductCommandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductCommandID");

                    b.HasIndex("CommandID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductCommands");

                    b.HasData(
                        new
                        {
                            ProductCommandID = 1,
                            CommandID = 1,
                            ProductID = 1,
                            Quantity = 4
                        },
                        new
                        {
                            ProductCommandID = 2,
                            CommandID = 1,
                            ProductID = 2,
                            Quantity = 4
                        },
                        new
                        {
                            ProductCommandID = 3,
                            CommandID = 2,
                            ProductID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ProductCommandID = 4,
                            CommandID = 2,
                            ProductID = 2,
                            Quantity = 2
                        },
                        new
                        {
                            ProductCommandID = 5,
                            CommandID = 3,
                            ProductID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ProductCommandID = 6,
                            CommandID = 3,
                            ProductID = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Store.Models.Command", b =>
                {
                    b.HasOne("Store.Models.Person", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store.Models.Person", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.HasOne("Store.Models.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Store.Models.ProductCommand", b =>
                {
                    b.HasOne("Store.Models.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
