@Store_HostAddress = http://localhost:5257

GET {{Store_HostAddress}}/api/price
Accept: application/json

###

GET {{Store_HostAddress}}/api/price/3
Accept: application/json

###

POST {{Store_HostAddress}}/api/price
Content-Type: application/json

{
    "priceID": 3,
    "value": 14.99,
    "currency": "USD"
}

###

PUT {{Store_HostAddress}}/api/price/3
Content-Type: application/json

{
    "priceID": 3,
    "value": 15,
    "currency": "USD",
    "discount": 40,
    "discountEndDate": "2026-11-01T00:00:00"
}

###

DELETE {{Store_HostAddress}}/api/price/3
Content-Type: application/json