@Store_HostAddress = http://localhost:5257

### Price - GET one

GET {{Store_HostAddress}}/api/price
Accept: application/json

### Price - GET all

GET {{Store_HostAddress}}/api/price/3
Accept: application/json

### Price - POST

POST {{Store_HostAddress}}/api/price
Content-Type: application/json

{
    "priceID": 3,
    "value": 14.99,
    "currency": "USD"
}

### Price - PUT

PUT {{Store_HostAddress}}/api/price/3
Content-Type: application/json

{
    "priceID": 3,
    "value": 15,
    "currency": "USD",
    "discount": 40,
    "discountEndDate": "2026-11-01T00:00:00"
}

### Price - DELETE

DELETE {{Store_HostAddress}}/api/price/3
Content-Type: application/json

###
### Product
###

### Product - GET one

GET {{Store_HostAddress}}/api/product/3
Accept: application/json

### Product - GET all

GET {{Store_HostAddress}}/api/product
Accept: application/json

### Product - POST

POST {{Store_HostAddress}}/api/product
Content-Type: application/json

{
    "ProductID": 3,
    "name": "GTA VI",
    "brand": "Rockstar Games",
    "description": "One of the most attended game of the world",
    "stock": 999,
    "priceID": 5
}

### Product - PUT

PUT {{Store_HostAddress}}/api/product/3
Content-Type: application/json

{
    "ProductID": 3,
    "name": "GTA VI",
    "brand": "Rockstar Games",
    "description": "One of the most attended game of the world",
    "stock": 12,
    "priceID": 5
}

### Product - DELETE

DELETE {{Store_HostAddress}}/api/product/5
Content-Type: application/json

###
### Person
###

### Person - GET one

GET {{Store_HostAddress}}/api/person/4
Accept: application/json

### Person - GET all

GET {{Store_HostAddress}}/api/person
Accept: application/json

### Person - POST

POST {{Store_HostAddress}}/api/person
Content-Type: application/json

{
    "personID": 4,
    "firstName": "Ezio",
    "lastName": "Auditore",
    "birthDate": "1459-06-24"
}

### Person - PUT

PUT {{Store_HostAddress}}/api/person/4
Content-Type: application/json

{
    "personID": 4,
    "firstName": "Tyler",
    "lastName": "Joseph",
    "birthDate": "1988-12-01"
}

### Person - DELETE

DELETE {{Store_HostAddress}}/api/person/4

###
### Command
###

### Command - GET one

GET {{Store_HostAddress}}/api/command/4
Accept: application/json

### Command - GET all

GET {{Store_HostAddress}}/api/command
Accept: application/json

### Command - POST

POST {{Store_HostAddress}}/api/command
Content-Type: application/json

{
    "commandID": 4,
    "totalQuanity": 1,
    "totalPrice": 0,
    "isPaid": false,
    "sellerID": 1,
    "buyerID": 3
}

### Command - PUT

PUT {{Store_HostAddress}}/api/command/4
Content-Type: application/json

{
    "commandID": 4,
    "totalQuanity": 5,
    "totalPrice": 0,
    "isPaid": false,
    "sellerID": 1,
    "buyerID": 3
}

### Command - DELETE

DELETE {{Store_HostAddress}}/api/command/4
Content-Type: application/json